package cejv569.medicationtracker.view.viewdata;

import cejv569.medicationtracker.model.datainterfaces.Contact;
import javafx.beans.property.ReadOnlyIntegerWrapper;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;

import java.sql.Timestamp;

/**
 *  ContactObservableData is a ViewObservableData subclass.  It is used to return contact email information obtained
 *  in the contacts form and sent to the model layer by ContacController.  This data object
 *  is initialized with regular java data types but also contains Observable object
 *  properties to bind/initialize javafx controls.
 */

public class ContactObservableData extends ViewObservableData implements Contact {

    private final static String ID_PROP_NAME = "id";
    private ReadOnlyIntegerWrapper id;

    private final static String DATE_PROP_NAME = "date";
    private SimpleObjectProperty<Timestamp> date;

    private final static String FULLNAME_PROP_NAME = "fullName";
    private SimpleStringProperty fullName;

    private final static String MESSAGE_PROP_NAME = "message";
    private SimpleStringProperty message;

    private final static String EMAIL_PROP_NAME = "email";
    private SimpleStringProperty email;

    /**
     * Constructor which receives all the contact email data retrieved from the contact form
     * and initialized by the ContactController instance.
     * @param id - int - primary key for the contact record in the contacts table
     * @param fullName - String - the senders full name
     * @param email  - String - The sender's email address
     * @param message -  String - The message contained in the email.
     * @param date      - SQl Timestamp value, as the date is generated by the mysql engine CURRENT_TIMESTAMP function,
     *                  however the field is included in case this field needs to be displayed
     *                  by the app.
     */

    public ContactObservableData(int id, String fullName, String email, String message, Timestamp date) {

        //create and initialize AccountObservableData values
        this.id = new ReadOnlyIntegerWrapper(this,ID_PROP_NAME,id);
        this.fullName = new SimpleStringProperty(this,FULLNAME_PROP_NAME,fullName);
        this.message = new SimpleStringProperty(this,MESSAGE_PROP_NAME,message);
        this.date = new SimpleObjectProperty<Timestamp>(this,DATE_PROP_NAME,date);
        this.email = new SimpleStringProperty(this,EMAIL_PROP_NAME,email);
    }

    //getters and setters

    @Override
    public int getId() {
        return id.get();
    }

    public ReadOnlyIntegerWrapper idProperty() {
        return id;
    }

    @Override
    public void setId(int id) {
        this.id.set(id);
    }

    @Override
    public Timestamp getDate() {
        return date.get();
    }

    public SimpleObjectProperty<Timestamp> dateProperty() {
        return date;
    }

    @Override
    public void setDate(Timestamp date) {
        this.date.set(date);
    }

    @Override
    public String getFullName() {
        return fullName.get();
    }

    public SimpleStringProperty fullNameProperty() {
        return fullName;
    }

    @Override
    public void setFullName(String fullName) {
        this.fullName.set(fullName);
    }

    @Override
    public String getMessage() {
        return message.get();
    }

    public SimpleStringProperty messageProperty() {
        return message;
    }

    @Override
    public void setMessage(String message) {
        this.message.set(message);
    }

    @Override
    public String getEmail() {
        return email.get();
    }

    public SimpleStringProperty emailProperty() {
        return email;
    }

    @Override
    public void setEmail(String email) {
        this.email.set(email);
    }
}
